package com.lab4;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class DatabaseManager {
    private Connection connection;
    private static final String DB_URL = "jdbc:h2:./lab4_database;MODE=PostgreSQL;NON_KEYWORDS=VALUE";
    private static final String DB_USER = "sa";
    private static final String DB_PASSWORD = "";

    public void connect() {
        try {
            Class.forName("org.h2.Driver");
            connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            System.out.println("Подключение к H2 Database установлено (файловая БД).");
        } catch (Exception e) {
            System.err.println("Ошибка подключения к БД: " + e.getMessage());
            System.exit(1);
        }
    }

    public void disconnect() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                System.out.println("Подключение закрыто. БД сохранена в файл.");
            }
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
        }
    }

    public void createAllTables() {
        String[] sqls = {
                "CREATE TABLE IF NOT EXISTS students (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "student_id VARCHAR(20) UNIQUE, " +
                        "full_name VARCHAR(200), " +
                        "direction VARCHAR(100), " +
                        "group_name VARCHAR(50), " +
                        "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",

                "CREATE TABLE IF NOT EXISTS listik_random (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "val INTEGER, " +
                        "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)",

                "CREATE TABLE IF NOT EXISTS listik_input (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "val VARCHAR(200), " +
                        "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
        };
        try (Statement stmt = connection.createStatement()) {
            for (String sql : sqls) {
                stmt.execute(sql);
            }
            System.out.println("Таблицы созданы.");
        } catch (SQLException e) {
            System.err.println("Ошибка создания таблиц: " + e.getMessage());
        }
    }

    // === Студенты ===
    public void saveStudent(String studentId, String fullName, String direction, String groupName) {
        String sql = "INSERT INTO students (student_id, full_name, direction, group_name) VALUES (?, ?, ?, ?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, studentId);
            ps.setString(2, fullName);
            ps.setString(3, direction);
            ps.setString(4, groupName);
            ps.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Ошибка сохранения студента: " + e.getMessage());
        }
    }

    public String getStudentById(String studentId) {
        String sql = "SELECT * FROM students WHERE student_id = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, studentId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return String.format("| %-8s | %-30s | %-30s | %-12s |",
                        rs.getString("student_id"),
                        rs.getString("full_name"),
                        rs.getString("direction"),
                        rs.getString("group_name"));
            }
        } catch (SQLException e) {
            System.err.println("Ошибка поиска: " + e.getMessage());
        }
        return null;
    }

    public boolean deleteStudent(String studentId) {
        String sql = "DELETE FROM students WHERE student_id = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, studentId);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Ошибка удаления: " + e.getMessage());
            return false;
        }
    }

    public List<String> getAllStudentsOrdered() {
        List<String> list = new ArrayList<>();
        String sql = "SELECT * FROM students ORDER BY full_name ASC";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                list.add(String.format("| %-8s | %-30s | %-30s | %-12s |",
                        rs.getString("student_id"),
                        rs.getString("full_name"),
                        rs.getString("direction"),
                        rs.getString("group_name")));
            }
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
        }
        return list;
    }

    // === Listik Random ===
    public void saveRandomValue(int value) {
        String sql = "INSERT INTO listik_random (val) VALUES (?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setInt(1, value);
            ps.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
        }
    }

    // === Listik Input ===
    public void saveInputValue(String value) {
        String sql = "INSERT INTO listik_input (val) VALUES (?)";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, value);
            ps.executeUpdate();
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
        }
    }

    public boolean deleteListikElement(String tableName, int id) {
        String sql = "DELETE FROM " + tableName + " WHERE id = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setInt(1, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            System.err.println("Ошибка удаления: " + e.getMessage());
            return false;
        }
    }

    // === Общие ===
    public List<String> getAllTables() {
        List<String> tables = new ArrayList<>();
        String sql = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'PUBLIC'";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) tables.add(rs.getString("table_name"));
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
        }
        return tables;
    }

    public ResultSet getTableData(String tableName) {
        try {
            return connection.createStatement().executeQuery("SELECT * FROM " + tableName + " ORDER BY id");
        } catch (SQLException e) {
            System.err.println("Ошибка: " + e.getMessage());
            return null;
        }
    }
}